// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'styled': string;
  'styled_input': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
