// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'block': string;
  'button': string;
  'header': string;
  'text': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
