// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cursor': string;
  'hint': string;
  'hint_left': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
