// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'back': string;
  'content': string;
  'flexBox': string;
  'statistic': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
