// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'company': string;
  'entity': string;
  'footer': string;
  'header': string;
  'image': string;
  'image__content': string;
  'name': string;
  'period': string;
  'period__content': string;
  'period__prefix': string;
  'realisation': string;
  'realisation__content': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
