// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'styled': string;
  'styled_accepted': string;
  'styled_confirmation': string;
  'styled_rejected': string;
}
export const cssExports: CssExports;
export default cssExports;
