// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'chevron': string;
  'chevron_inverted': string;
  'dropdown': string;
  'heading': string;
  'inner': string;
  'inner_active': string;
  'inner_empty': string;
  'option': string;
  'option__checkbox': string;
  'option__text': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
