// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'icon': string;
  'input': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
