// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'gallery': string;
  'meta': string;
  'meta__tags': string;
  'nextTag': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
