// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'heading': string;
  'heading__content': string;
  'icon': string;
  'inner': string;
  'textarea': string;
  'textarea_error': string;
  'textarea_readonly': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
