// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'tab': string;
  'tab_active': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
