// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'comitet': string;
  'gimc': string;
  'images': string;
}
export const cssExports: CssExports;
export default cssExports;
