// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'grey': string;
  'styled': string;
  'styled_disabled': string;
  'white': string;
}
export const cssExports: CssExports;
export default cssExports;
