// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fit': string;
  'flex': string;
  'full': string;
  'half': string;
  'leadHelper': string;
  'link': string;
  'table__columnHeader_label': string;
  'table__columnHeader_main': string;
  'table__columnHeader_secondary': string;
  'table__columnHeader_sorting': string;
  'table__content': string;
  'table__footer': string;
  'table__footerControl': string;
  'table__footerInfo': string;
  'table__footerPagination': string;
  'table__footerPaginationController': string;
  'table__header': string;
  'table__loader': string;
  'table__paginator': string;
  'table__paginatorHeading': string;
  'table__row': string;
  'table__row_main': string;
  'table__row_secondary': string;
  'table__wrapper': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
