// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'category': string;
  'category_active': string;
  'icon': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
