// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'filtration': string;
  'heading': string;
  'navigation': string;
  'search': string;
  'table': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
