// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'footer': string;
  'header': string;
  'tag': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
