// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'spin': string;
  'styled': string;
  'styled_small': string;
}
export const cssExports: CssExports;
export default cssExports;
