// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'data': string;
  'footer': string;
  'metadata': string;
  'social': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
