// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'heading': string;
  'inner': string;
  'nextTag': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
